name: 'Run PIDIFF'
description: 'Compare two disk images and generate an rsync batch file for incremental updates'
branding:
  icon: 'git-compare'
  color: 'blue'

inputs:
  base_image:
    description: 'Path to base image file'
    required: true
  updated_image:
    description: 'Path to updated image file'
    required: true
  partition:
    description: 'Rootfs partition number'
    required: false
    default: '2'
  output:
    description: 'Output batch file path'
    required: false
  tar:
    description: 'Create tar archive containing batch and batch.sh files'
    required: false
    default: 'false'
  rsync_options:
    description: 'Additional rsync options to pass through (space-separated, e.g., "--verbose --exclude=*.pyc")'
    required: false

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install -y kpartx rsync
      shell: bash
    - name: Run pidiff
      run: |
        PIDIFF_ARGS=()
        if [[ -n "${{ inputs.partition }}" ]]; then
          PIDIFF_ARGS+=("--partition=${{ inputs.partition }}")
        fi
        if [[ -n "${{ inputs.output }}" ]]; then
          PIDIFF_ARGS+=("--output=${{ inputs.output }}")
        fi
        if [[ "${{ inputs.tar }}" == "true" ]]; then
          PIDIFF_ARGS+=("--tar")
        fi
        if [[ -n "${{ inputs.rsync_options }}" ]]; then
          # Split rsync_options by spaces and add each option to PIDIFF_ARGS
          # This handles options like --verbose --exclude=*.pyc --exclude-from=file
          # Note: For options with spaces or special characters, use YAML quotes
          read -ra RSYNC_OPTS <<< "${{ inputs.rsync_options }}"
          PIDIFF_ARGS+=("${RSYNC_OPTS[@]}")
        fi
        sudo ${{ github.action_path }}/../pidiff.sh "${PIDIFF_ARGS[@]}" "${{ inputs.base_image }}" "${{ inputs.updated_image }}"
      shell: bash

