name: shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Shellcheck pimod.sh
        run: shellcheck -s bash -x pimod.sh
