name: shellcheck

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Shellcheck pimod.sh
        run: shellcheck -s bash -x pimod.sh

      - name: Shellcheck modules/*.sh
        run: cd modules && shellcheck -s bash -x *.sh

      - name: Shellcheck stages/*.sh
        run: cd stages && shellcheck -s bash -x *.sh
